env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
settings:
  import/resolver:
    node:
      extensions: ['.js','.jsx','.ts','.tsx']
  react:
    version: 'detect'
