env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  no-unused-vars: 0
  no-use-before-define: 0
  '@typescript-eslint/no-unused-vars': 1
  '@typescript-eslint/no-use-before-define': 1
settings:
  import/resolver:
    node:
      extensions: ['.js','.jsx','.ts','.tsx']
  react:
    version: 'detect'
